name: User Service Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub (optional)
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t vkr-user-service:latest .

      - name: Save Docker image as tar
        run: |
          docker save -o vkr-user-service.tar vkr-user-service:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vkr-user-service
          path: vkr-user-service.tar