name: User Service CD lol

on:
  workflow_run:
    workflows: ["User Service Docker CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: vkr-user-service
          path: .

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

          # Copy Docker image to server
          scp vkr-user-service.tar $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH

          # Load Docker image and run container
          ssh $REMOTE_USER@$REMOTE_HOST << EOF
            cd $REMOTE_PATH
            docker load -i vkr-user-service.tar
            docker stop vkr-user-service || true
            docker rm vkr-user-service || true
            docker run -d --name vkr-user-service -p 8080:8080 vkr-user-service:latest
          EOF